# Generated by Django 2.2.1 on 2019-05-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_auto_20190510_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self-checkout', 'самовивіз'), ('delivery', 'доставка')], default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AIP_status', 'Прийнятий в обробку'), ('IP_status', 'В обробці'), ('PAID_status', 'Оплачено')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=9),
        ),
    ]
