# Generated by Django 2.2.1 on 2019-05-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_auto_20190510_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buying_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
