# Generated by Django 2.2.1 on 2019-05-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_auto_20190518_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
