# Generated by Django 2.2.1 on 2019-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_property_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='count_product',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
