# Generated by Django 2.2.2 on 2019-06-18 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0015_property_count_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=ecomapp.models.image_folder)),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
            },
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('reduction', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecomapp.models.image_folder)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Знишку',
                'verbose_name_plural': 'Знишки',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='bramd',
        ),
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти2'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='bramd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='album_cover',
            field=models.ImageField(default=None, upload_to=ecomapp.models.image_folder_cover),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
        migrations.AddField(
            model_name='reduction',
            name='product',
            field=models.ManyToManyField(to='ecomapp.Product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecomapp.Product'),
        ),
    ]
