# Generated by Django 2.2.2 on 2019-06-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_auto_20190618_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
