# Generated by Django 2.2.2 on 2019-06-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_delete_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='Product',
            new_name='product',
        ),
    ]
