# Generated by Django 2.2.2 on 2019-06-24 14:38

from django.db import migrations, models
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0018_auto_20190618_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(upload_to=ecomapp.models.image_folder_album),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=9)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('delivery', models.CharField(choices=[('nova_poshta', 'Нова пошта'), ('ukr_poshta', 'Укр-пошта')], max_length=40)),
                ('address', models.CharField(max_length=255)),
                ('buying_type', models.CharField(choices=[('self-checkout', 'самовивіз'), ('delivery', 'доставка')], max_length=40)),
                ('status', models.CharField(choices=[('AIP_status', 'Прийнятий в обробку'), ('IP_status', 'В обробці'), ('PAID_status', 'Оплачено')], default='AIP_status', max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('product', models.ManyToManyField(to='ecomapp.Product')),
            ],
        ),
    ]
