# Generated by Django 2.2.2 on 2019-06-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0021_auto_20190625_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
    ]
