# Generated by Django 2.2.2 on 2019-06-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0022_auto_20190625_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Сторінки сайта',
                'verbose_name_plural': 'Сторінку сайту',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=9, verbose_name='Номер телефону +380'),
        ),
    ]
