# Generated by Django 2.2.2 on 2019-06-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0023_auto_20190625_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Сторінку сайта', 'verbose_name_plural': 'Сторінки сайта'},
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
